// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tyvt5U2ZZPlD3TKqmyLxp2-_ErzwfNs',
    appId: '1:2363741169:web:0e17c43ce68af9b408ea50',
    messagingSenderId: '2363741169',
    projectId: 'marwaappesi',
    authDomain: 'marwaappesi.firebaseapp.com',
    storageBucket: 'marwaappesi.firebasestorage.app',
    measurementId: 'G-W80LKHPQQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCVcgYZcrLgrntKgIvOv8dUz5LLrp4zGk',
    appId: '1:2363741169:android:4d951664246bcee408ea50',
    messagingSenderId: '2363741169',
    projectId: 'marwaappesi',
    storageBucket: 'marwaappesi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt2LWRQ4WXy7bY7TDXlEoFfskrFmipiDs',
    appId: '1:2363741169:ios:10eab1a2b3b002b508ea50',
    messagingSenderId: '2363741169',
    projectId: 'marwaappesi',
    storageBucket: 'marwaappesi.firebasestorage.app',
    iosBundleId: 'com.example.appweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt2LWRQ4WXy7bY7TDXlEoFfskrFmipiDs',
    appId: '1:2363741169:ios:10eab1a2b3b002b508ea50',
    messagingSenderId: '2363741169',
    projectId: 'marwaappesi',
    storageBucket: 'marwaappesi.firebasestorage.app',
    iosBundleId: 'com.example.appweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3tyvt5U2ZZPlD3TKqmyLxp2-_ErzwfNs',
    appId: '1:2363741169:web:470e41fe42ef9f5208ea50',
    messagingSenderId: '2363741169',
    projectId: 'marwaappesi',
    authDomain: 'marwaappesi.firebaseapp.com',
    storageBucket: 'marwaappesi.firebasestorage.app',
    measurementId: 'G-Z5M5RYDPBD',
  );

}